name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN" }} | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker image build . --file Dockerfile --tag tux.tools
        docker push tux.tools
